// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"MakeAppointmentMOBILEHUB","alias":"$LATEST","description":"Bot to book a dentist appointment.","bot-template":"bot-appointments","commands-help":["I would like to book an appointment","Book an appointment","I would like to see the dentist","I would like to schedule a visit","Make appointment"],"region":"us-east-1"}],
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"xeqvwieqo8","name":"testAPI","description":"","endpoint":"https://xeqvwieqo8.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:b0ac2512-0faa-4b91-9a6c-9ad5c2ae357e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'test-hosting-mobilehub-144987786',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1x68catub3rtq.cloudfront.net',
    'aws_mobile_analytics_app_id': 'ca9dfe73e8f54fea8ddf214101e73384',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a484ae67-02fa-4668-ad34-a1b3031197da',
    'aws_project_name': 'test',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'test-deployments-mobilehub-144987786',
    'aws_resource_name_prefix': 'test-mobilehub-144987786',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'test-userfiles-mobilehub-144987786',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_NcfwtAheB',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1cab0tna7pqfhqaggcq3t2nj2p',
}

export default awsmobile;
